### ISSUE TITLE
轻微滑动后视频重新播放

### ISSUE THREAD

**Issue by aaronsu** [18702953620/DouDemo#11]
Page2Activity中 如果当前页码为1, 轻微滑动固定后页码依然为1,那么 他依然会release 
改前
View view = snapHelper.findSnapView(layoutManager);
                        recyclerView.getChildAdapterPosition(view);
                        JZVideoPlayer.releaseAllVideos();
                        RecyclerView.ViewHolder viewHolder = recyclerView.getChildViewHolder(view);
                        if (viewHolder != null && viewHolder instanceof VideoViewHolder) {
                            ((VideoViewHolder) viewHolder).mp_video.startVideo();
                        }

改后
 View view = snapHelper.findSnapView(layoutManager);
                        //当前固定后的item position
                        int tmpposition = recyclerView.getChildAdapterPosition(view);
                        if (position != tmpposition) {  //如果当前position  和 上一次固定后的position 相同,说明是同一个,只不过滑动了一点点,然后又释放了
                            JZVideoPlayer.releaseAllVideos();
                            RecyclerView.ViewHolder viewHolder = recyclerView.getChildViewHolder(view);
                            if (viewHolder != null && viewHolder instanceof VideoViewHolder) {
                                ((VideoViewHolder) viewHolder).mp_video.startVideo();
                            }
                            position = tmpposition;
                        }

第一次提这个 不知道格式对不.

**Comment by wang2793312458** [comment]
position是从哪获取，public void onScrollStateChanged(RecyclerView recyclerView, int position) {}
吗

**Comment by aaronsu** [comment]
对的
View view = snapHelper.findSnapView(layoutManager);
int tmpposition = recyclerView.getChildAdapterPosition(view);
我是这么做的.

**Comment by wang2793312458** [comment]
3Q

**Comment by wang2793312458** [comment]
暂停  功能是不是不能用

**Comment by wang2793312458** [comment]
点击视频放大在哪控制

**Comment by 18702953620** [comment]
@aaronsu 已修复该问题，感谢

**Comment by 18702953620** [comment]
@wang2793312458  请查看MyVideoPlayer#rl_touch_help 点击事件相关代码

**Comment by lucf1103** [comment]
java.lang.NullPointerException: Attempt to invoke virtual method 'android.view.ViewParent android.view.View.getParent()' on a null object reference
        at android.support.v7.widget.RecyclerView.getChildViewHolder(RecyclerView.java:4447)
        at com.ch.doudemo.activity.Page2Activity$1.onScrollStateChanged(Page2Activity.java:91)
        at android.support.v7.widget.RecyclerView.dispatchOnScrollStateChanged(RecyclerView.java:4881)
        at android.support.v7.widget.RecyclerView.setScrollState(RecyclerView.java:1467)
        at android.support.v7.widget.RecyclerView$ViewFlinger.run(RecyclerView.java:5030)

这样操作会有个小问题，当数据为0条的时候会报空指针！ 
我加了：
 //当前固定后的item position
                        int position = recyclerView.getChildAdapterPosition(view);
                        if (urlList.size() == 0) {
                            return;
                        }
