### ISSUE TITLE
请问解决了内存溢出的问题吗

### ISSUE THREAD

**Issue by zsfzbc** [18702953620/DouDemo#3]
如果一直不停的滑动, 内存占用会一直增加吗?

**Comment by 18702953620** [comment]
RecyclerView 相对viewpager的话 内存占用会小点，2者都有回收机制，有出现内存溢出？

**Comment by DebugZeng** [comment]
上下滑切换视频（一）的问题，，如果一直不停的滑动, 那fragment一直增加，对象也一直在内存里面 ，，那会导致内存不断增大，这问题要怎么解决呢？

**Comment by 18702953620** [comment]
@DebugZeng viewpager有自己的回收机制，详细可阅读viewpager的源码
